version: 1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -f Dockerfile -t david/hello-world:$CIRCLE_TAG .
      #- run: docker push david/hello-world:$CIRCLE_BRANCH
    filters:
      branches:
        - master
      tags:
        only: v/^\d+\.\d+\.\d+$/
