version: 1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo $VERSION
      #- run: docker build -f Dockerfile -t david/hello-world:$CIRCLE_BRANCH .
      #- run: docker push david/hello-world:$CIRCLE_BRANCH
